/**
 * Export the TypeScript engine's output on fixed inputs, so the Python analysis
 * port (../analysis) can prove it ranks jobs identically.
 *
 *   npm run reference:export
 *
 * Writes ../analysis/reference/ts_reference.json. The Python parity test reads
 * it and fails if any parse, score or rank differs.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { seedJobs, SEED_REPORTS } from "@/lib/data/seed";
import { rankJobs } from "@/lib/engine/rank";
import { buildJob } from "@/lib/engine/scoring";
import { parseWithFallback } from "@/lib/parser/fallback";
import { generateReports } from "@/lib/data/generator";
import { AGEING_POINTS_PER_DAY } from "@/lib/taxonomy";
import type { Job } from "@/lib/engine/types";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "analysis", "reference", "ts_reference.json");

const LAMBDAS = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1];

// Ageing is a fixed policy; a fixed reference clock keeps the reference file
// reproducible. The Python parity test reads these two values back.
const REFERENCE_NOW = "2026-09-22T23:59:00+09:30";

function snapshot(jobs: Job[]) {
  const runs = [];
  for (const batching of [true, false]) {
    for (const lambda of LAMBDAS) {
      const r = rankJobs(jobs, {
        lambda,
        batching,
        ageing: AGEING_POINTS_PER_DAY,
        now: REFERENCE_NOW,
      });
      runs.push({
        lambda,
        batching,
        ranked: r.ranked.map((x) => ({
          id: x.job.id,
          needScore: x.need.score,
          efficiencyScore: x.efficiency.score,
          needRank: x.needRank,
          efficiencyRank: x.efficiencyRank,
          finalRank: x.finalRank,
          estimatedStartDays: x.estimatedStartDays,
        })),
      });
    }
  }
  return runs;
}

// A larger, varied queue from the generator, parsed by the fallback parser.
const generated = generateReports(60, "parity").map((g, i) => ({
  id: `G${String(i).padStart(3, "0")}`,
  rawText: g.rawText,
}));
const genJobs: Job[] = [];
for (const g of generated) {
  const { job } = buildJob({
    id: g.id,
    rawText: g.rawText,
    reportedAt: "2026-09-20T00:00:00+09:30",
    report: parseWithFallback(g.rawText),
  });
  if (job) genJobs.push(job);
}

// The fail-safe hold: the same seed queue, with every report in which the parser
// recognised no hazard marked as not yet read by a person.
const heldJobs: Job[] = seedJobs().map((j) => ({ ...j, needsReading: j.report.urgency_flags.length === 0 }));

const texts = [...SEED_REPORTS.map((s) => s.rawText), ...generated.map((g) => g.rawText)];

const reference = {
  note: "Generated by nt-housing-triage/scripts/export-reference.ts. Do not edit by hand.",
  ageing: AGEING_POINTS_PER_DAY,
  now: REFERENCE_NOW,
  seed: {
    inputs: SEED_REPORTS,
    runs: snapshot(seedJobs()),
  },
  held: {
    note: "Seed queue with needsReading = (no urgency flags recognised).",
    inputs: SEED_REPORTS,
    runs: snapshot(heldJobs),
  },
  generated: {
    inputs: generated.map((g) => ({ ...g, reportedAt: "2026-09-20T00:00:00+09:30" })),
    runs: snapshot(genJobs),
  },
  parses: texts.map((t) => {
    const p = parseWithFallback(t);
    return {
      text: t,
      category: p.category,
      safety_level: p.safety_level,
      urgency_flags: p.urgency_flags,
      occupant_vulnerability: p.occupant_vulnerability,
      trade_required: p.trade_required,
      community: p.community,
    };
  }),
};

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify(reference, null, 1));
console.log(`wrote ${out}`);
